import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DynamicHeroImage from "../components/native/DynamicHeroImage";
import Navbar from "../components/native/Navbar";
import Footer from "../components/native/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="   ">
          <Navbar />
        </div>

        {children}
      </body>
    </html>
  );
}
